name: "Deploy site"

on:
  push:
    branches:
      - "ghactions"

jobs:
  build:
    name: Build lektor website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      
      - name: Install Lektor
        run: |
          python -m pip install -r requirements.txt
      
      - shell: bash
        env:
          SUPER_SECRET: ${{ secrets.SuperSecret }}
        run: |
          echo "$SUPER_SECRET"
      
      - name: Build lektor website
        run: lektor build
